### ISSUE TITLE
主键改成独立字段

### ISSUE THREAD

**Issue by Smart-Hypercube** [ustclug/hackergame#15]
现在 ctf.Problem 的主键是 slug 字段，这在 ORM 下非常不便，会导致在后端修改 slug 时会令人意外地产生两道几乎完全相同的题目，而且其他表的外键引用也很难级联修改。主键应该采用几乎不可能有修改需求的字段，如递增数字或 UUID

**Comment by zzh1996** [comment]
对

**Comment by Smart-Hypercube** [comment]
已解决，但旧的数据库无法直接 migrate 到新的版本，因此清空重做了 migrations
