### ISSUE TITLE
科大统一身份认证登录使用 GID 作为唯一标识

### ISSUE THREAD

**Issue by zzh1996** [ustclug/hackergame#17]
现在同一个人可以搞出来多个账号

**Comment by Smart-Hypercube** [comment]
已修复，现在起同一个人不能搞出更多账号了。
如果之前只有一个账号，在下一次登录时系统会自动把标识更新为 GID。
如果之前有多个账号，仍然可以用不同的登录名登录之前存在的各个账号。
