### ISSUE TITLE
限制昵称长度

### ISSUE THREAD

**Issue by zzh1996** [ustclug/hackergame#27]
要不然大家都开始刷屏。。。

**Comment by Smart-Hypercube** [comment]
现在 Django 对用户名就有 150 字符的限制，去年看来，这个限制也还好，可以随意发挥，但又没有严重干扰到排行榜页面阅读体验

**Comment by zzh1996** [comment]
限制在普通屏幕显示的一行之内会不会好一些

**Comment by Smart-Hypercube** [comment]
你提议多少字符，或者什么规则呢？

**Comment by zzh1996** [comment]
我提议让这个字符数成为一个可以配置的参数

**Comment by Smart-Hypercube** [comment]
我反对把所有难以合理地决定的事情都搞成“可配置的”，因为：
1. 现在也不是不可配置，只是配置的难易程度有区别而已
2. 不同重要性的配置就是应该用不同复杂程度来修改，最重要（每个部署几乎一定会不同）的一些配置要整理在一起，其他配置可以通过自己修改代码来实现
3. 如果所有“不同人可能有不同口味”的东西都搞进配置文件里，最后会导致颜色、边距、字号、表格线宽等各种琐碎细节全进去
4. 150 是一个说得过去的用户名长度限制，也是 Django 默认值，除非有新的提案并且确实有必要采纳，否则没必要改
