### ISSUE TITLE
提供查询用户信息的接口

### ISSUE THREAD

**Issue by zzh1996** [ustclug/hackergame#46]
输入：用户 id，即 token 最前面的数字
返回：token 前 10 位、用户组、用户是否已经同意 terms、用户填写的所有其他信息

**Comment by Smart-Hypercube** [comment]
terms 状态有点难加上，而且好像不急需，先关闭 issue

**Comment by zzh1996** [comment]
实际上问题不大。不过我的想法是如果一个人没同意 terms 就放进群里，在逻辑上有点奇怪
