### ISSUE TITLE
“打开题目”按钮

### ISSUE THREAD

**Issue by zzh1996** [ustclug/hackergame#48]
“打开题目”按钮改成“打开或下载题目”？然后按钮颜色希望可以做得更醒目一些（例如蓝色）

否则当题目描述中有其他链接时，选手很容易忽略还有一个可以下载的文件

**Comment by Smart-Hypercube** [comment]
我本来打算让每道题目有“下载”（文件）和“打开”（链接）两个属性，如果都有就显示两个按钮
