### ISSUE TITLE
用 js 把题目描述里所有链接都搞成在新 tab 打开

### ISSUE THREAD

**Issue by zzh1996** [ustclug/hackergame#50]

**Comment by Smart-Hypercube** [comment]
有两种方法：
1. 用 JS 找出题目描述中的所有外部链接，修改属性
2. 在 markdown 渲染阶段做这件事

基本上一样简单，我想想具体利弊

**Comment by zzh1996** [comment]
如果在渲染阶段做的话，python-markdown 写插件很容易，有人写过类似的功能，可以参考 https://github.com/kriwil/markdown-newtab/blob/master/markdown_newtab/__init__.py#L20
