### ISSUE TITLE
中途停止比赛再继续后，曲线图有误

### ISSUE THREAD

**Issue by Smart-Hypercube** [ustclug/hackergame#69]

**Comment by zzh1996** [comment]
@Smart-Hypercube 非管理员通过 API 拿到的 trigger 不完整，需要后端修复

**Comment by Smart-Hypercube** [comment]
@zzh1996 这是 feature，非管理员只能看到已经发生过的事件，不能预知未来的事件（以便管理员提前设置或调整）如果要继续保持这个 feature 的话，正解是修改前端判断 endtime 的逻辑，如果发现获取到的最后一个 trigger 是 true，就按比赛正在进行处理

**Comment by zzh1996** [comment]
ok, 我来修复一下
