### ISSUE TITLE
增加前 N 名的分数变化曲线图

### ISSUE THREAD

**Issue by Smart-Hypercube** [ustclug/hackergame#7]
不是非常必要

**Comment by zzh1996** [comment]
你可以提供一个 API，然后其他人来写前端

**Comment by zzh1996** [comment]
你写一个 json API，返回前 N 名的 ctf_solve，包括解题时间和题目分数，再加上画图的时间范围（开始时间和 min(当前时间, 结束时间)）

**Comment by Smart-Hypercube** [comment]
API:
POST /admin/submission/
{"method": "get_board", "args": {"limit": 100}} 这会得到总排行榜前 100 名
{"method": "get_user_progress", "args": {"user": 1}} 这会得到 1 号用户的解题进展（每道题和每个 flag 的解决时间）
可以参考 board.html 这个 template

**Comment by zzh1996** [comment]
我把分数曲线图写好推 chart 分支了，你把权限处理好可以 merge 一下
