### ISSUE TITLE
比赛结束后无法查看排行榜

### ISSUE THREAD

**Issue by emon100** [ustclug/hackergame#75]
这是个 Bug 还是 Feature? 如图，排名图表上的日期没有随时比赛结束而停止。
![image](https://user-images.githubusercontent.com/12141326/73423448-1dddf780-4367-11ea-828a-c7c765260f24.png)

**Comment by zzh1996** [comment]
@Smart-Hypercube 我检查了一下，原因是你加了一个「请勿删除此项——wzb」的 trigger，时间在比赛截止之后，导致排行榜认为比赛仍在进行中

**Comment by Smart-Hypercube** [comment]
这是 bug，但是是最初设计时的 feature 导致的，所以有点难解决。 ~我先把出现 bug 的页面解决了~ 可能等到 2020 再修吧
